src/Entity/Category.php
<?php

namespace App\Entity;

use App\Repository\CategoryRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;


#[ORM\Entity(repositoryClass: CategoryRepository::class)]
class Category
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
   /**
    * @ORM\Column(type="string", nullable=true)
  */
  private $image;


    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_creation = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $date_update = null;

    #[ORM\Column(length: 255)]
    private ?string $status = null;

    #[ORM\Column(length: 255)]
    private ?string $sexe = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

   
public function getImage(): ?string
    {
        if (!$this->image) {
            return null;
        }
        if (strpos($this->image, '/') !== false) {
            return $this->image;
        }
        return sprintf('uploads/parfum/%s', $this->image);
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;
    
        return $this;
    }


    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): static
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getDateUpdate(): ?\DateTimeInterface
    {
        return $this->date_update;
    }

    public function setDateUpdate(\DateTimeInterface $date_update): static
    {
        $this->date_update = $date_update;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getSexe(): ?string
    {
        return $this->sexe;
    }

    public function setSexe(string $sexe): static
    {
        $this->sexe = $sexe;

        return $this;
    }
    // public function __toString()
    // {
    //     return $this->nom.' '.$this->description.' '.$this->image.' '.$this->date_creation.' '.$this->date_update.' '.$this->status.' '.$this->sexe;
    // }

    public function __toString()
    {
        return $this->nom;
    }
}

src/Form/CategoryType.php
<?php

namespace App\Form;

use App\Entity\Category;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Validator\Constraints\File;
class CategoryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
            /*->add('nom')
            ->add('description')
            ->add('image')
            >add('image', FileType::class, [
                'label' => 'Image',
                'required' => false,
            ])
            ->add('date_update', null, [
                'widget' => 'single_text',
            ])
            ->add('status')
            ->add('sexe')

        ;*/
        $builder
        ->add('nom')
        ->add('description')
        ->add('image', FileType::class, [
            'label' => 'Image',
            'mapped' => false,
            'required' => false,
            'constraints' => [
                new File([
                    'maxSize' => '2048k',
                    'mimeTypes' => [
                        'image/png',
                        'image/jpeg',
                        'image/pjpeg',
                    ],
                    'mimeTypesMessage' => 'Please upload a valid image',
                ])
            ],
        ])
        ->add('date_creation', null, [
            'widget' => 'single_text',
        ])
        ->add('date_update', null, [
            'widget' => 'single_text',
        ])
       
        ->add('status')
        ->add('sexe');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Category::class,
        ]);
    }
}

src/Controller/CategoryController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Form\CategoryType;
use App\Repository\CategoryRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;


#[Route('/category')]
class CategoryController extends AbstractController
{
    private $targetDirectory;
    private $entityManager;
    public function __construct(ParameterBagInterface $params , EntityManagerInterface $entityManager,)
    {
        $this->entityManager = $entityManager;
        $this->targetDirectory = $params->get('parfum_uploads_directory');
    }
    #[Route('/', name: 'app_category_index', methods: ['GET'])]
    public function index(CategoryRepository $categoryRepository): Response
    {
        return $this->render('category/index.html.twig', [
            'categories' => $categoryRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_category_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $category = new Category();
        $form = $this->createForm(CategoryType::class, $category);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $entityManager->persist($category);
            $uploadedFile = $form->get('image')->getData();
            if ($uploadedFile) {
                $newFileName = md5(uniqid()) . '.' . $uploadedFile->guessExtension();
                $uploadedFile->move($this->targetDirectory, $newFileName);
                $category->setImage($newFileName);
            }

            $entityManager->flush();

            return $this->redirectToRoute('app_category_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('category/new.html.twig', [
            'category' => $category,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_category_show', methods: ['GET'])]
    public function show(Category $category): Response
    {
        return $this->render('category/show.html.twig', [
            'category' => $category,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_category_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Category $category, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(CategoryType::class, $category);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $uploadedFile = $form->get('image')->getData();
                if ($uploadedFile) {
                    $newFileName = md5(uniqid()) . '.' . $uploadedFile->guessExtension();
                    $uploadedFile->move($this->targetDirectory, $newFileName);
                    $category->setImage($newFileName);
                }
                  

            $entityManager->flush();

            return $this->redirectToRoute('app_category_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('category/edit.html.twig', [
            'category' => $category,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_category_delete', methods: ['POST'])]
    public function delete(Request $request, Category $category, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$category->getId(), $request->getPayload()->get('_token'))) {
            $entityManager->remove($category);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_category_index', [], Response::HTTP_SEE_OTHER);
    }

    
}

templates/category/_delete_form.html.twig
<form method="post" action="{{ path('app_category_delete', {'id': category.id}) }}" onsubmit="return confirm('tu veux supprimer cette categorie ');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ category.id) }}">
    <button class="btn">Delete</button>
</form>

templates/category/_form.html.twig
{# {{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}
 #}

 {{ form_start(form) }}
<div>
<label for="category_name" class="form-label">
{{ form_label(form.nom) }}
</label>
{{ form_widget(form.nom, {'attr':{'class':'form-control'}}) }}
</div>

<div>
<label for="category_descreption" class="form-label">
{{ form_label(form.description) }}
</label>
{{ form_widget(form.description, {'attr':{'class':'form-control'}}) }}
</div>

<div>
<label for="category_image" class="form-label">
{{ form_label(form.image) }}
</label>
{{ form_widget(form.image, {'attr':{'class':'form-control'}}) }}
</div>

<div>
<label for="category_date_creation" class="form-label">
{{ form_label(form.date_creation) }}
</label>
{{ form_widget(form.date_creation, {'attr':{'class':'form-control'}}) }}
</div>

<div>
<label for="category_dateupadate" class="form-label">
{{ form_label(form.date_update) }}
</label>
{{ form_widget(form.date_update, {'attr':{'class':'form-control'}}) }}
</div>


<div>
<label for="category_status" class="form-label">
{{ form_label(form.status) }}
</label>
{{ form_widget(form.status, {'attr':{'class':'form-control'}}) }}
</div>

<div>
<label for="category_sexe" class="form-label">
{{ form_label(form.sexe) }}
</label>
{{ form_widget(form.sexe, {'attr':{'class':'form-control'}}) }}
</div>
<div>&nbsp;</div>
<div>
<button class="btn btn-primary">{{ button_label|default('Save') }}</button>
</div>
{{ form_end(form) }}

templates/category/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Category{% endblock %}

{% block body %}
    <h1>Edit Category</h1>

    {{ include('category/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_category_index') }}">back to list</a>

    {{ include('category/_delete_form.html.twig') }}
{% endblock %}

templates/category/index.html.twig
{# {% extends 'base.html.twig' %}

{% block title %}Category index{% endblock %}

{% block body %}
    <h1>Category index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Description</th>
                <th>Image</th>
                <th>Date_creation</th>
                <th>Date_update</th>
                <th>Status</th>
                <th>Sexe</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for category in categories %}
            <tr>
                <td>{{ category.id }}</td>
                <td>{{ category.nom }}</td>
                <td>{{ category.description }}</td>
                <td>  category.image </td>
                <td>{{ category.dateCreation ? category.dateCreation|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ category.dateUpdate ? category.dateUpdate|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ category.status }}</td>
                <td>{{ category.sexe }}</td>
                <td>
                    <a href="{{ path('app_category_show', {'id': category.id}) }}">show</a>
                    <a href="{{ path('app_category_edit', {'id': category.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_category_new') }}">Create new</a>
{% endblock %} #}
{% extends 'base.html.twig' %}
{% block title %}LES Categorie des Parfum{% endblock %}
{% block body %}
<h1>Les Categorie des Parfum</h1>
    <a  class="btn btn-success" href="{{ path('app_category_new') }}">Ajoute une Categorie</a>

<table class="table">
<thead>
<tr>
                <th>Id#</th>
                <th>Nom</th>
                <th>Description</th>
                <th>Image</th>
                <th>Date_creation</th>
                <th>Date_update</th>
                <th>Status</th>
                <th>Sexe</th>
                <th>actions</th>
</tr>
</thead>
<tbody>
{% for category in categories %}
            <tr>
                <td>{{ category.id }}</td>
                <td>{{ category.nom }}</td>
                <td>{{ category.description }}</td>
                <td> {% if category.image %}
                            <img src="{{ asset( category.image) }}" height="50px"  />
                        {% else %}
                            <span>No image available</span>
                        {% endif %} </td>
                <td>{{ category.dateCreation ? category.dateCreation|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ category.dateUpdate ? category.dateUpdate|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ category.status }}</td>
                <td>{{ category.sexe }}</td>
                <td>
                    {# <a href="{{ path('app_category_edit', {'id': category.id}) }}">Edit</a>
                    <a href="{{ path('app_category_delete', {'id': category.id}) }}">Delete</a>
                    <a href="{{ path('app_category_show', {'id': category.id}) }}">Show</a> #}
               <div class="btn-group" role="group" aria-label="Actions">
                    <a class="btn btn-warning" href="{{ path('app_category_edit', {'id': category.id}) }}">Modif</a>
                    <a class="btn btn-danger" href="{{ path('app_category_delete', {'id': category.id}) }}">Supprime</a>
                    <a class="btn btn-primary" href="{{ path('app_category_show', {'id': category.id}) }}">Consulte</a>
             </div>


                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">>no records found</td>
            </tr>
        {% endfor %}
</tbody>
</table>
{% endblock %}

templates/category/new.html.twig
{#% extends 'base.html.twig' %}

{% block title %}New Category{% endblock %}

{% block body %}
    <h1>Create new Category</h1>

    {{ include('category/_form.html.twig') }}

    <a href="{{ path('app_category_index') }}">back to list</a>
{% endblock %} #}

{% extends 'base.html.twig' %}
{% block title %}Nouveaux categories{% endblock %}
{% block body %}
<h1>Cree nouveaux Categorie</h1>
{{ include('category/_form.html.twig') }}
<div>&nbsp;</div>
<a href="{{ path('app_category_index') }}" class="btn btn-secondary">back to
list</a>
{% endblock %}

templates/category/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Category{% endblock %}

{% block body %}
    <h1>Category</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ category.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ category.nom }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ category.description }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>  {% if  category.image is not null %}
                <img src="{{ asset(category.image) }}" alt="Image">
                    {% else %}
                        Aucune image disponible
                    {% endif %}</td>
            </tr>
            <tr>
                <th>Date_creation</th>
                <td>{{ category.dateCreation ? category.dateCreation|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Date_update</th>
                <td>{{ category.dateUpdate ? category.dateUpdate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ category.status }}</td>
            </tr>
            <tr>
                <th>Sexe</th>
                <td>{{ category.sexe }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_category_index') }}">Retour à la liste</a>

    <a href="{{ path('app_category_edit', {'id': category.id}) }}">Modif</a>

    {{ include('category/_delete_form.html.twig') }}
{% endblock %}