src/Entity/Promotion.php
<?php

namespace App\Entity;

use App\Repository\PromotionRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PromotionRepository::class)]
class Promotion
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Parfum $parfum = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    #[ORM\Column(length: 255)]
    private ?string $nomPromotio = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_debut = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_fin = null;

    #[ORM\Column]
    private ?int $pourcentage = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getParfum(): ?Parfum
    {
        return $this->parfum;
    }

    public function setParfum(?Parfum $parfum): static
    {
        $this->parfum = $parfum;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }

    public function getNomPromotio(): ?string
    {
        return $this->nomPromotio;
    }

    public function setNomPromotio(string $nomPromotio): static
    {
        $this->nomPromotio = $nomPromotio;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getDateDebut(): ?\DateTimeInterface
    {
        return $this->date_debut;
    }

    public function setDateDebut(\DateTimeInterface $date_debut): static
    {
        $this->date_debut = $date_debut;

        return $this;
    }

    public function getDateFin(): ?\DateTimeInterface
    {
        return $this->date_fin;
    }

    public function setDateFin(\DateTimeInterface $date_fin): static
    {
        $this->date_fin = $date_fin;

        return $this;
    }

    public function getPourcentage(): ?int
    {
        return $this->pourcentage;
    }

    public function setPourcentage(int $pourcentage): static
    {
        $this->pourcentage = $pourcentage;

        return $this;
    }
    public function __toString()
    {
        return $this->nomPromotio.' '.$this->description.' '.$this->date_debut.' '.$this->date_fin.' '.$this->pourcentage;
    }
}

src/Form/PromotionType.php
<?php

namespace App\Form;

use App\Entity\Category;
use App\Entity\Parfum;
use App\Entity\Promotion;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PromotionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nomPromotio')
            ->add('description')
            ->add('date_debut', null, [
                'widget' => 'single_text',
            ])
            ->add('date_fin', null, [
                'widget' => 'single_text',
            ])
            ->add('pourcentage')
            ->add('parfum', EntityType::class, [
                'class' => Parfum::class,
                'choice_label' => 'id',
            ])
            ->add('category', EntityType::class, [
                'class' => Category::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Promotion::class,
        ]);
    }
}

src/Controller/PromotionController.php
<?php

namespace App\Controller;

use App\Entity\Promotion;
use App\Form\PromotionType;
use App\Repository\PromotionRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/promotion')]
class PromotionController extends AbstractController
{
    #[Route('/', name: 'app_promotion_index', methods: ['GET'])]
    public function index(PromotionRepository $promotionRepository): Response
    {
        return $this->render('promotion/index.html.twig', [
            'promotions' => $promotionRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_promotion_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $promotion = new Promotion();
        $form = $this->createForm(PromotionType::class, $promotion);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($promotion);
            $entityManager->flush();

            return $this->redirectToRoute('app_promotion_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('promotion/new.html.twig', [
            'promotion' => $promotion,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_promotion_show', methods: ['GET'])]
    public function show(Promotion $promotion): Response
    {
        return $this->render('promotion/show.html.twig', [
            'promotion' => $promotion,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_promotion_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Promotion $promotion, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PromotionType::class, $promotion);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_promotion_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('promotion/edit.html.twig', [
            'promotion' => $promotion,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_promotion_delete', methods: ['POST'])]
    public function delete(Request $request, Promotion $promotion, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$promotion->getId(), $request->getPayload()->get('_token'))) {
            $entityManager->remove($promotion);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_promotion_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/promotion/_delete_form.html.twig
<form method="post" action="{{ path('app_promotion_delete', {'id': promotion.id}) }}" onsubmit="return confirm('tu es sur de supprimer cette promotion?')";">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ promotion.id) }}">
    <button class="btn">Delete</button>
</form>

templates/promotion/_form.html.twig
{# {{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) #}
{{form_start(form) }}
<div>
<label for="promotion_name" class="form-label">
{{ form_label(form.nomPromotio) }}
</label>
{{ form_widget(form.nomPromotio, {'attr':{'class':'form-control'}}) }}
</div>
<div>
<label for="promotion_description" class="form-label">
{{ form_label(form.description) }}
</label>
{{ form_widget(form.description, {'attr':{'class':'form-control'}}) }}
</div>

<div>
<label for="promotion_dateDebut" class="form-label">
{{ form_label(form.date_debut) }}
</label>
{{ form_widget(form.date_debut, {'attr':{'class':'form-control'}}) }}
</div>

<div>
<label for="promotion_dateFin" class="form-label">
{{ form_label(form.date_fin) }}
</label>
{{ form_widget(form.date_fin, {'attr':{'class':'form-control'}}) }}
</div>

<div>
<label for="promotion_pourcentage" class="form-label">
{{ form_label(form.pourcentage) }}
</label>
{{ form_widget(form.pourcentage, {'attr':{'class':'form-control'}}) }}
</div>

<div>
<label for="promotion_parfum" class="form-label">
{{ form_label(form.parfum)}}
</label>
{{ form_widget(form.parfum, {'attr':{'class':'form-control'}}) }}
</div>
<div>
<label for="promotion_catgory" class="form-label">
{{ form_label(form.category) }}
</label>
{{ form_widget(form.category, {'attr':{'class':'form-control'}}) }}

</div>
<div>&nbsp;</div>
<div>
<button class="btn btn-primary">{{ button_label|default('Save') }}</button>
</div>
{{ form_end(form) }}

templates/promotion/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Promotion{% endblock %}

{% block body %}
    <h1>Edit Promotion</h1>

    {{ include('promotion/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_promotion_index') }}">Retour a liste</a>

    {{ include('promotion/_delete_form.html.twig') }}
{% endblock %}

templates/promotion/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Promotion index{% endblock %}

{% block body %}
    <h1>Liste de Promotions</h1>
<a class="btn btn-success" href="{{ path('app_promotion_new') }}">Ajoute nouveau promotion</a>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>NomPromotio</th>
                <th>Description</th>
                <th>Date_debut</th>
                <th>Date_fin</th>
                <th>Pourcentage</th>
                <th>Parfum</th>
                <th>Categorie de parfum </th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for promotion in promotions %}
            <tr>
                <td>{{ promotion.id }}</td>
                <td>{{ promotion.nomPromotio }}</td>
                <td>{{ promotion.description }}</td>
                <td>{{ promotion.dateDebut ? promotion.dateDebut|date('Y-m-d') : '' }}</td>
                <td>{{ promotion.dateFin ? promotion.dateFin|date('Y-m-d') : '' }}</td>
                <td>{{ promotion.pourcentage }}</td>
                <td>{{ promotion.Parfum. nom}}</td>
                <td>{{ promotion.category.nom }}</td>
                <td>
                    {# <a href="{{ path('app_promotion_show', {'id': promotion.id}) }}">show</a>
                    <a href="{{ path('app_promotion_edit', {'id': promotion.id}) }}">edit</a> #}

                <div class="btn-group" role="group" aria-label="Actions">
                <a class="btn btn-primary" href="{{ path('app_promotion_show', {'id': promotion.id}) }}">Consulte</a>
                <a class="btn btn-warning" href="{{ path('app_promotion_edit', {'id': promotion.id}) }}">Modif</a>
                <a class="btn btn-danger" href="{{ path('app_promotion_delete', {'id': promotion.id}) }}">Supprimer</a>
                </div>

                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

   
{% endblock %}

templates/promotion/new.html.twig
{# {% extends 'base.html.twig' %}

{% block title %}New Promotion{% endblock %}

{% block body %}
    <h1>Create new Promotion</h1>

    {{ include('promotion/_form.html.twig') }}

    <a href="{{ path('app_promotion_index') }}">back to list</a>
{% endblock %} #}


{% extends 'base.html.twig' %}
{% block title %}Nouveau  Promotion{% endblock %}
{% block body %}
<h1>Cree nouveaupromotion</h1>
{{ include('promotion/_form.html.twig') }}
<div>&nbsp;</div>
<a href="{{ path('app_promotion_index') }}" class="btn btn-secondary">Retour a la liste</a>
{% endblock %}

templates/promotion/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Promotion{% endblock %}

{% block body %}
    <h1>Promotion</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ promotion.id }}</td>
            </tr>
            <tr>
                <th>NomPromotio</th>
                <td>{{ promotion.nomPromotio }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ promotion.description }}</td>
            </tr>
            <tr>
                <th>Date_debut</th>
                <td>{{ promotion.dateDebut ? promotion.dateDebut|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Date_fin</th>
                <td>{{ promotion.dateFin ? promotion.dateFin|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Pourcentage</th>
                <td>{{ promotion.pourcentage }}</td>
            </tr>
        </tbody>
    </table>

<div class="btn-group" role="group" aria-label="Actions">
                <a class="btn btn-primary" href="{{ path('app_promotion_index') }}">Retour a liste </a>
                <a class="btn btn-warning" href="{{ path('app_promotion_edit', {'id': promotion.id}) }}">Modif</a>
</div>
    {# <a href="{{ path('app_promotion_index') }}">back to list</a> #}

    {# <a href="{{ path('app_promotion_edit', {'id': promotion.id}) }}">edit</a> #}

    {{ include('promotion/_delete_form.html.twig') }}
{% endblock %}